#!/usr/bin/env bash
# A script for Installing , configuring and starting the server

sudo apt update -y
sudo apt install -y nginx
echo 'Hello World!' > /var/www/html/index.nginx-debian.html
sudo service nginx start
