#!/usr/bin/env bash
# Configure Nginx server so it redirects me to another page.

sudo apt-get -y update
sudo apt-get -y install -y nginx
sudo ufw allow 'Nginx HTTP'
echo "Hello World" | sudo tee /var/www/html/index.nginx-debian.html
sudo sed -i '/listen 80 default_server/a rewrite ^/redirect_me https://twitter.com/teddy_10000 permanent;' /etc/nginx/sites-available/default
sudo service nginx reload
