#!/usr/bin/env bash
# Configure Nginx server so that /redirect_me redirects me and adding custom page

sudo apt update -y
sudo apt install -y nginx
sudo ufw allow 'Nginx HTTP'
echo "Hello World" | sudo tee /var/www/html/index.nginx-debian.html
echo "This page doesnot exist" | sudo tee /var/www/html/custom404.html
sudo sed -i '/listen 80 default_server/a rewrite ^/redirect_me https://twitter.com/teddy_10000 permanent;' /etc/nginx/sites-available/default
sudo sed -i '/listen 80 default_server/a error_page 404 /custom404.html;' /etc/nginx/sites-available/default
sudo service nginx reload
