#!/usr/bin/env bash
# Creating a script to install and configure an HAProxy 
# Configure HAProxy to send traffic to web-01 and web-02 servers
# Using a roundrobin algorithm to make the distributions 
# Installing and configuring HAproxy.
sudo apt-get -y update
apt-get -y install haproxy

# editting the config file
server_config=\
"
frontend  skytech-frontend
        bind *:80
        mode http
        default_backend skytech-backend
backend skytech-backend
        balance roundrobin
        server 63210-web-01 34.227.92.34:80 check
        server 63210-web-02 107.23.87.108:80 check
"
echo "$server_config" | sudo tee -a /etc/haproxy/haproxy.cfg

# enabling haproxy to start by init script

echo "ENABLED=1" | sudo tee -a /etc/default/haproxy

sudo service haproxy restart
